services:
  web:
    # Build the image from the Dockerfile in the current directory
    build: .

    ports:
      # Bind the FastAPI application on port 8000
      - "8080:8080"

    volumes:
      # Sync the working directory with the `/app` directory in the container
      - .:/app
      # Ignore the virtual environment directory
      - /app/.venv
    
    # Run the FastAPI application in development mode
    command: ["fastapi", "dev", "src/webapp", "--port", "8080", "--host", "0.0.0.0"]
    
    environment:
      # Set the environment variable to force polling for the watchfiles
      - WATCHFILES_FORCE_POLLING=true

