name: "Set Up Python Environment"

inputs:
  python-version:
    description: "Python version to use"
    required: true
  uv-version:
    description: "uv version to use"
    required: false
    default: "0.4.20"

runs:
  using: composite
  steps:
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true

    - name: Install project and dependencies
      run: uv sync --frozen --dev
      shell: bash
