name: "Set Up Python Environment"

inputs:
  python-version:
    description: "Python version to use"
    required: true

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.22"
        enable-cache: true

    - name: Install project and dependencies
      run: uv sync --frozen --dev
      shell: bash
