name: lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-python-env
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45.0.1
        with:
          files: |
            **.py
            **.ipynb
      - name: Check style
        run: |
          uv tool run ruff check ${{ steps.changed-files.outputs.all_changed_files }}
