name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    # defaults:
    #   run:
    #     shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          uv run python -m pytest
